# show reconstruct image

In [1]:
import pickle
import yaml
import os
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import torch.nn.functional as F

In [2]:
########################################################################
# load config
########################################################################
with open("./config.yaml", 'rb') as f:
    config = yaml.load(f)

/home/hiroki/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  """


In [3]:
########################################################################
# Setting I/O path
########################################################################
# input dirs
INPUT_ROOT = config['IO_OPTION']['INPUT_ROOT']
dev_path = INPUT_ROOT + "/dev_data"
add_dev_path = INPUT_ROOT + "/add_dev_data"
eval_path = INPUT_ROOT + "/eval_test"
MODEL_DIR = config['IO_OPTION']['OUTPUT_ROOT'] + '/models'
# machine type
MACHINE_TYPE = config['IO_OPTION']['MACHINE_TYPE']
machine_types = os.listdir(dev_path)
# output dirs
OUTPUT_ROOT = config['IO_OPTION']['OUTPUT_ROOT']
RESULT_DIR = config['IO_OPTION']['OUTPUT_ROOT'] + '/result'
RECONS_OUTDIR = OUTPUT_ROOT +'/eval_reconstruct_img'
PKL_DIR = OUTPUT_ROOT +'/pkl'
os.makedirs(MODEL_DIR, exist_ok=True)

# eval

## import library

In [4]:
########################################################################
# import default python-library
########################################################################
import os
import glob
import csv
import re
import itertools
import sys
from collections import defaultdict
########################################################################


########################################################################
# import additional python-library
########################################################################
import numpy
from sklearn import metrics
import common as com
import pytorch_modeler as modeler
from pytorch_model import DAGMM as Model
import torch.utils.data
import yaml
yaml.warnings({'YAMLLoadWarning': False})
import matplotlib.pyplot as plt
import seaborn as sns
from tqdm import tqdm
########################################################################
import eval_functions as eval_func
from pytorch_utils import to_var

## Setting

In [5]:
########################################################################
# load config
########################################################################
with open("./config.yaml", 'rb') as f:
    config = yaml.load(f)

/home/hiroki/anaconda3/lib/python3.7/site-packages/ipykernel/ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [6]:
########################################################################
# Setting seed
########################################################################
modeler.set_seed(42)

In [7]:
########################################################################
# Setting I/O path
########################################################################
# input dirs
INPUT_ROOT = config['IO_OPTION']['INPUT_ROOT']
dev_path = INPUT_ROOT + "/dev_data"
add_dev_path = INPUT_ROOT + "/add_dev_data"
eval_path = INPUT_ROOT + "/eval_test"
MODEL_DIR = config['IO_OPTION']['OUTPUT_ROOT'] + '/models'
# machine type
MACHINE_TYPE = config['IO_OPTION']['MACHINE_TYPE']
machine_types = os.listdir(dev_path)
# output dirs
OUTPUT_ROOT = config['IO_OPTION']['OUTPUT_ROOT']
RESULT_DIR = config['IO_OPTION']['OUTPUT_ROOT'] + '/result'
RECONS_OUTDIR = OUTPUT_ROOT +'/eval_reconstruct_img'
os.makedirs(MODEL_DIR, exist_ok=True)

In [8]:
########################################################################
# for original function
########################################################################
param = {}
param["dev_directory"] = dev_path
param["eval_directory"] = eval_path
param["model_directory"] = MODEL_DIR
param["result_directory"] = RESULT_DIR
param["result_file"] = 'result.csv'

from sklearn.metrics import mean_squared_error as mse

def calc_time_anomaly(x, y, label, file_name):
    fig = plt.figure(figsize=(10,5)) # width, height
    fig.suptitle('label={}'.format(int(label)))
    time_anomaly = np.zeros((x.shape[0]))
    for frame in range(x.shape[0]):
        time_anomaly[frame] = mse(y[frame,:],x[frame,:])
    plt.plot(time_anomaly)
    plt.title(f'label:{label}')

time_anomaly.mean()

plt.plot(time_anomaly)

plt.figure(figsize=(5,5))
plt.imshow(np.abs(x-y), aspect='auto')

## run eval

In [9]:
def make_reconstruct_img(x, y, label, file_name):
    fig = plt.figure(figsize=(10,5)) # width, height
    fig.suptitle('label={}'.format(int(label)))
    ax1 = fig.add_subplot(121, title='x') # 明示的にAxesを作成する
    sns.heatmap(x.T, ax=ax1) # ax1を参照するようにする
    ax2 = fig.add_subplot(122, title='y')
    sns.heatmap(y.T, ax=ax2)
    fig.savefig('{}.png'.format(file_name))

In [10]:
mode = 'dev'

In [11]:
from torchvision import transforms
import preprocessing as prep

class extract_waveform(object):
    """
    wavデータロード(波形)
    
    Attributes
    ----------
    sound_data : waveform
    """
    def __init__(self, sound_data=None):
        self.sound_data = sound_data
    
    def __call__(self, sample):
        self.sound_data = com.file_load(sample['wav_name'],
                                        sr=config['preprocessing']['sample_rate'],
                                        mono=config['preprocessing']['mono'])
        self.sound_data = self.sound_data[0]
        self.label = np.array(sample['label'])
        self.wav_name = sample['wav_name']
        
        return {'feature': self.sound_data, 'label': self.label, 'wav_name': self.wav_name}

class ToTensor(object):
    """
    Convert ndarrays in sample to Tensors.
    """

    def __call__(self, sample):
        feature, label, wav_name = sample['feature'], sample['label'], sample['wav_name']
        
        return {'feature': torch.from_numpy(feature).float(), 'label': torch.from_numpy(label), 'wav_name': wav_name}

class DCASE_task2_Dataset_test(torch.utils.data.Dataset):
    '''
    Attribute
    ----------
    
    '''
    
    def __init__(self, file_list, transform=None):
        self.transform = transform
        self.file_list = file_list
        
    def __len__(self):
        return len(self.file_list)
    
    def __getitem__(self, idx):
        file_path = self.file_list[idx]
        # ファイル名でlabelを判断
        if "normal" in file_path:
            label = 0
        else:
            label = 1
        
        sample = {'wav_name':file_path, 'label':np.array(label)}
        sample = self.transform(sample)
        
        return sample

def make_dataloader_train(paths):
    transform = transforms.Compose([
        extract_waveform(),
        ToTensor()
    ])
    dataset = DCASE_task2_Dataset_test(paths, transform=transform)
    
    train_loader = torch.utils.data.DataLoader(
        dataset=dataset,
        batch_size=config['fit']['batch_size'],
        shuffle=True,
        num_workers=2,
        pin_memory=True
        )
    
    return test_loader
    
def make_dataloader_test(paths):
    transform = transforms.Compose([
        extract_waveform(),
        ToTensor()
    ])
    dataset = DCASE_task2_Dataset_test(paths, transform=transform)
    
    test_loader = torch.utils.data.DataLoader(
        dataset=dataset,
        batch_size=config['fit']['batch_size'],
        shuffle=False,
        num_workers=2,
        pin_memory=True
        )
    
    return test_loader

In [12]:
############################################################################
# make path set and train/valid split
############################################################################
'''
train_paths[machine_type]['train' or 'valid'] = path
'''
dev_train_paths = {}
add_train_paths = {}
train_paths = {}

for machine_type in machine_types:
    # dev train
    dev_train_paths = ["{}/{}/train/".format(dev_path, machine_type) + file for file in os.listdir("{}/{}/train".format(dev_path, machine_type))]
    dev_train_paths = sorted(dev_train_paths)
    # add_dev train
    add_train_paths = ["{}/{}/train/".format(add_dev_path, machine_type) + file for file in os.listdir("{}/{}/train".format(add_dev_path, machine_type))]
    add_train_paths = sorted(add_train_paths)
    # valid
    dev_valid_paths = ["{}/{}/test/".format(dev_path, machine_type) + file for file in os.listdir("{}/{}/test".format(dev_path, machine_type))]
    dev_valid_paths = sorted(dev_valid_paths)
    
    train_paths[machine_type] = {}
    train_paths[machine_type]['train'] = dev_train_paths + add_train_paths
    train_paths[machine_type]['valid'] = dev_valid_paths

In [13]:
#def run_eval(param, mode):
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

# make output result directory
os.makedirs(RESULT_DIR, exist_ok=True)

# load base directory
dirs = com.select_dirs(param=param, mode=mode)

# initialize lines in csv for AUC and pAUC
csv_lines = []


# loop of the base directory
for idx, target_dir in enumerate(dirs):
    com.logger.info("===========================")
    com.logger.info("[{idx}/{total}] {dirname}".format(
        dirname=target_dir, idx=idx+1, total=len(dirs)))

    machine_type = os.path.split(target_dir)[1]

    com.logger.info("============== MODEL LOAD ==============")

    model_file = "{model}/{machine_type}_model.pth".format(
        model=param["model_directory"],
        machine_type=machine_type)

    if not os.path.exists(model_file):
        com.logger.error("{} model not found ".format(machine_type))
        sys.exit(-1)

    # define AE model
    model = Model(sample_rate=config['preprocessing']['sample_rate'],
                  window_size=config['preprocessing']['window_size'],
                  hop_size=config['preprocessing']['hop_size'],
                  mel_bins=config['preprocessing']['mel_bins'],
                  fmin=config['preprocessing']['fmin'],
                  fmax=config['preprocessing']['fmax'],
                  latent_size=config['fit']['latent_size'],
                  mixture_size=config['fit']['mixture_size']).to(device)
    model.eval()
    model.load_state_dict(torch.load(model_file))

    if mode:
        # results by type
        csv_lines.append([machine_type])
        csv_lines.append(["id", "AUC", "pAUC"])
        performance = []

    machine_id_list = eval_func.get_machine_id_list_for_test(target_dir)
    recons_outpath = RECONS_OUTDIR + '/' + machine_type
    os.makedirs(recons_outpath, exist_ok=True)
    
    # calc train GMM param
    com.logger.info(f"============== CALC GMM PARAM : {machine_type} ==============")
    
    train_loader = make_dataloader_test(train_paths[machine_type]['train'])
    N = 0
    mu_sum = 0
    cov_sum = 0
    gamma_sum = 0
    with torch.no_grad():
        for sample in tqdm(train_loader):
            input_data = sample['feature']
            input_data = to_var(input_data)
            nn_out = model(input_data, device)
            tr_phi, tr_mu, tr_cov = model.compute_gmm_params(nn_out['z'], nn_out['gamma'])
            tr_phi, tr_mu, tr_cov = tr_phi.to('cpu'), tr_mu.to('cpu'), tr_cov.to('cpu')
            batch_gamma_sum = torch.sum(nn_out['gamma'].to('cpu'), dim=0).to('cpu')
            gamma_sum += batch_gamma_sum
            mu_sum += tr_mu * batch_gamma_sum.unsqueeze(-1) # keep sums of the numerator only
            cov_sum += tr_cov * batch_gamma_sum.unsqueeze(-1).unsqueeze(-1) # keep sums of the numerator only
            N += input_data.size(0)
    train_phi = gamma_sum / N
    train_mu = mu_sum / gamma_sum.unsqueeze(-1)
    train_cov = cov_sum / gamma_sum.unsqueeze(-1).unsqueeze(-1)
    print("N:",N)
    print("phi :\n",train_phi)
    print("mu :\n",train_mu)
    print("cov :\n",train_cov)
    
    # evaluation
    for id_str in machine_id_list:

        # load list of test files
        test_files, y_true = eval_func.test_file_list_generator(target_dir, id_str, mode)

        # setup anomaly score file path
        anomaly_score_csv = \
            "{result}/anomaly_score_{machine_type}_{id_str}.csv"\
            .format(result=param["result_directory"],
                    machine_type=machine_type,
                    id_str=id_str)
        anomaly_score_list = []

        com.logger.info(
            "============== BEGIN TEST FOR A MACHINE ID ==============")

        y_pred = []
        anomaly_count = 0
        normal_count = 0
        
        test_loader = make_dataloader_test(test_files)
        start_idx = 0
        end_idx = 0
        slicing = None
        with torch.no_grad():
            for it, data in enumerate(tqdm(test_loader)):
                try:
                    feature = data['feature']
                    feature = to_var(feature)
                    label = data['label']
                    file_path = data['wav_name']
                    # reconstruction through auto encoder in pytorch
                    with torch.no_grad():
                        nn_out = model(feature)
                        z, _ = nn_out['z'], nn_out['gamma']
                        sample_energy, cov_diag = model.compute_energy(z, phi=to_var(train_phi), mu=to_var(train_mu), cov=to_var(train_cov), size_average=False)
                        preds = sample_energy.data.cpu().numpy()
                        if it == 0:
                            y_pred = preds.copy()
                        else:
                            y_pred = np.concatenate([y_pred, preds], axis=0)

                    for idx in range(len(file_path)):
                        anomaly_score_list.append([os.path.basename(file_path[idx]), preds[idx]])
                except FileNotFoundError:
                    com.logger.error("file broken!!")

        # save anomaly score
        eval_func.save_csv(save_file_path=anomaly_score_csv,
                           save_data=anomaly_score_list)
        com.logger.info(
            "anomaly score result ->  {}".format(anomaly_score_csv))

        if mode:
            # append AUC and pAUC to lists
            auc = metrics.roc_auc_score(y_true, y_pred)
            p_auc = metrics.roc_auc_score(
                y_true, y_pred, max_fpr=config["etc"]["max_fpr"])
            csv_lines.append([id_str.split("_", 1)[1], auc, p_auc])
            performance.append([auc, p_auc])
            com.logger.info("AUC : {}".format(auc))
            com.logger.info("pAUC : {}".format(p_auc))

        com.logger.info(
            "============ END OF TEST FOR A MACHINE ID ============")

    if mode:
        # calculate averages for AUCs and pAUCs
        averaged_performance = numpy.mean(
            numpy.array(performance, dtype=float), axis=0)
        csv_lines.append(["Average"] + list(averaged_performance))
        csv_lines.append([])

if mode:
    # output results
    result_path = "{result}/{file_name}".format(
        result=param["result_directory"],
        file_name=param["result_file"])
    com.logger.info("AUC and pAUC results -> {}".format(result_path))
    eval_func.save_csv(save_file_path=result_path, save_data=csv_lines)

2020-11-30 18:13:32,777 - INFO - load_directory <- development
2020-11-30 18:13:32,779 - INFO - ===========================
2020-11-30 18:13:32,779 - INFO - [1/6] /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyCar
2020-11-30 18:13:32,780 - INFO - ============== MODEL LOAD ==============
2020-11-30 18:13:33,716 - INFO - ============== CALC GMM PARAM : ToyCar ==============
100%|██████████| 55/55 [00:05<00:00, 10.50it/s]
2020-11-30 18:13:38,959 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyCar_id_01
2020-11-30 18:13:38,966 - INFO - test_file  num : 601
2020-11-30 18:13:38,967 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/5 [00:00<?, ?it/s]

N: 7000
phi :
 tensor([3.3541e-05, 9.9992e-01, 4.3399e-05])
mu :
 tensor([[ 0.0985, -0.0885,  0.0955, -0.1044, -0.1037,  0.2007],
        [-0.0246,  0.0311, -0.0232,  0.0162,  0.0272,  0.0713],
        [ 0.1417, -0.1353,  0.1362, -0.1435, -0.1439,  0.2440]])
cov :
 tensor([[[ 0.0545, -0.0517,  0.0499, -0.0510, -0.0510,  0.0513],
         [-0.0517,  0.0542, -0.0513,  0.0513,  0.0513, -0.0513],
         [ 0.0499, -0.0513,  0.0548, -0.0503, -0.0523,  0.0514],
         [-0.0510,  0.0513, -0.0503,  0.0553,  0.0513, -0.0514],
         [-0.0510,  0.0513, -0.0523,  0.0513,  0.0549, -0.0514],
         [ 0.0513, -0.0513,  0.0514, -0.0514, -0.0514,  0.0570]],

        [[ 0.0065, -0.0035,  0.0019, -0.0027, -0.0029,  0.0016],
         [-0.0035,  0.0057, -0.0031,  0.0029,  0.0030, -0.0015],
         [ 0.0019, -0.0031,  0.0067, -0.0021, -0.0038,  0.0016],
         [-0.0027,  0.0029, -0.0021,  0.0072,  0.0031, -0.0015],
         [-0.0029,  0.0030, -0.0038,  0.0031,  0.0065, -0.0016],
         [ 0.0016

100%|██████████| 5/5 [00:01<00:00,  4.90it/s]
2020-11-30 18:13:39,990 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyCar_id_01.csv
2020-11-30 18:13:39,994 - INFO - AUC : 0.5487877063175868
2020-11-30 18:13:39,994 - INFO - pAUC : 0.5305994068837432
2020-11-30 18:13:39,995 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:39,996 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyCar_id_02
2020-11-30 18:13:40,004 - INFO - test_file  num : 602
2020-11-30 18:13:40,005 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00,  5.85it/s]
2020-11-30 18:13:40,864 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyCar_id_02.csv
2020-11-30 18:13:40,867 - INFO - AUC : 0.5693310657596372
2020-11-30 18:13:40,867 - INFO - pAUC : 0.5479174125790667
2020-11-30 18:13:40,868 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:40,868 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyCar_id_03
2020-11-30 18:13:40,876 - INFO - test_file  num : 602
2020-11-30 18:13:40,877 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00,  6.32it/s]
2020-11-30 18:13:41,671 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyCar_id_03.csv
2020-11-30 18:13:41,674 - INFO - AUC : 0.69578231292517
2020-11-30 18:13:41,675 - INFO - pAUC : 0.5898675259577515
2020-11-30 18:13:41,675 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:41,676 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyCar_id_04
2020-11-30 18:13:41,685 - INFO - test_file  num : 602
2020-11-30 18:13:41,685 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00,  6.38it/s]
2020-11-30 18:13:42,473 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyCar_id_04.csv
2020-11-30 18:13:42,476 - INFO - AUC : 0.5758956916099773
2020-11-30 18:13:42,477 - INFO - pAUC : 0.5433225921947726
2020-11-30 18:13:42,477 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:42,478 - INFO - ===========================
2020-11-30 18:13:42,479 - INFO - [2/6] /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyConveyor
2020-11-30 18:13:42,480 - INFO - ============== MODEL LOAD ==============
2020-11-30 18:13:43,354 - INFO - ============== CALC GMM PARAM : ToyConveyor ==============
100%|██████████| 47/47 [00:04<00:00, 11.16it/s]
2020-11-30 18:13:47,570 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyConveyor_id_01
2020-11-30 18:13:47,580 - INFO - test_file  n

N: 6000
phi :
 tensor([1.2804e-04, 9.9981e-01, 5.7611e-05])
mu :
 tensor([[-0.5070,  0.4904, -0.5016, -0.4833, -0.4816,  0.1463],
        [ 0.0299, -0.0248,  0.0204,  0.0283,  0.0233,  0.0723],
        [-0.1660,  0.1743, -0.1719, -0.1711, -0.1679,  0.2665]])
cov :
 tensor([[[ 0.0431, -0.0422,  0.0427,  0.0427,  0.0425, -0.0336],
         [-0.0422,  0.0436, -0.0433, -0.0418, -0.0429,  0.0336],
         [ 0.0427, -0.0433,  0.0441,  0.0422,  0.0434, -0.0336],
         [ 0.0427, -0.0418,  0.0422,  0.0436,  0.0420, -0.0336],
         [ 0.0425, -0.0429,  0.0434,  0.0420,  0.0438, -0.0336],
         [-0.0336,  0.0336, -0.0336, -0.0336, -0.0336,  0.0337]],

        [[ 0.0046, -0.0024,  0.0028,  0.0034,  0.0026, -0.0014],
         [-0.0024,  0.0064, -0.0048, -0.0015, -0.0044,  0.0016],
         [ 0.0028, -0.0048,  0.0059,  0.0015,  0.0045, -0.0016],
         [ 0.0034, -0.0015,  0.0015,  0.0063,  0.0015, -0.0014],
         [ 0.0026, -0.0044,  0.0045,  0.0015,  0.0063, -0.0016],
         [-0.0014

100%|██████████| 10/10 [00:01<00:00,  8.02it/s]
2020-11-30 18:13:48,831 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyConveyor_id_01.csv
2020-11-30 18:13:48,835 - INFO - AUC : 0.5018996062992126
2020-11-30 18:13:48,836 - INFO - pAUC : 0.4976516093383064
2020-11-30 18:13:48,836 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:48,838 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyConveyor_id_02
2020-11-30 18:13:48,848 - INFO - test_file  num : 1136
2020-11-30 18:13:48,850 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:01<00:00,  7.33it/s]
2020-11-30 18:13:50,083 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyConveyor_id_02.csv
2020-11-30 18:13:50,086 - INFO - AUC : 0.2644419642857143
2020-11-30 18:13:50,086 - INFO - pAUC : 0.47824639724310775
2020-11-30 18:13:50,087 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:50,087 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/ToyConveyor_id_03
2020-11-30 18:13:50,099 - INFO - test_file  num : 1135
2020-11-30 18:13:50,100 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/9 [00:00<?, ?it/s]

100%|██████████| 9/9 [00:01<00:00,  7.50it/s]
2020-11-30 18:13:51,304 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_ToyConveyor_id_03.csv
2020-11-30 18:13:51,307 - INFO - AUC : 0.5418976101078729
2020-11-30 18:13:51,308 - INFO - pAUC : 0.49032468530525314
2020-11-30 18:13:51,308 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:51,308 - INFO - ===========================
2020-11-30 18:13:51,309 - INFO - [3/6] /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/fan
2020-11-30 18:13:51,309 - INFO - ============== MODEL LOAD ==============
2020-11-30 18:13:52,122 - INFO - ============== CALC GMM PARAM : fan ==============
100%|██████████| 51/51 [00:04<00:00, 10.87it/s]
2020-11-30 18:13:56,820 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/fan_id_00
2020-11-30 18:13:56,826 - INFO - test_file  num : 489
2020-11-3

N: 6521
phi :
 tensor([6.1461e-04, 4.1947e-03, 9.9519e-01])
mu :
 tensor([[-0.2808,  0.2429,  0.2806,  0.0402,  0.2839,  0.1863],
        [-0.2550,  0.2073,  0.2968,  0.2404,  0.3633,  0.1132],
        [-0.0101,  0.0113,  0.0084, -0.0255,  0.0185,  0.0505]])
cov :
 tensor([[[ 0.0107, -0.0093, -0.0095,  0.0085, -0.0080,  0.0074],
         [-0.0093,  0.0107,  0.0103, -0.0084,  0.0101, -0.0070],
         [-0.0095,  0.0103,  0.0125, -0.0068,  0.0121, -0.0078],
         [ 0.0085, -0.0084, -0.0068,  0.0140, -0.0042,  0.0064],
         [-0.0080,  0.0101,  0.0121, -0.0042,  0.0143, -0.0079],
         [ 0.0074, -0.0070, -0.0078,  0.0064, -0.0079,  0.0089]],

        [[ 0.0076, -0.0076, -0.0069,  0.0097, -0.0073,  0.0024],
         [-0.0076,  0.0119,  0.0118, -0.0100,  0.0137, -0.0022],
         [-0.0069,  0.0118,  0.0131, -0.0078,  0.0156, -0.0023],
         [ 0.0097, -0.0100, -0.0078,  0.0179, -0.0071,  0.0023],
         [-0.0073,  0.0137,  0.0156, -0.0071,  0.0200, -0.0023],
         [ 0.0024

100%|██████████| 4/4 [00:00<00:00,  6.05it/s]
2020-11-30 18:13:57,491 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_fan_id_00.csv
2020-11-30 18:13:57,494 - INFO - AUC : 0.816478149100257
2020-11-30 18:13:57,494 - INFO - pAUC : 0.5583818157218239
2020-11-30 18:13:57,495 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:57,495 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/fan_id_02
2020-11-30 18:13:57,502 - INFO - test_file  num : 441
2020-11-30 18:13:57,502 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 4/4 [00:00<00:00,  6.35it/s]
2020-11-30 18:13:58,136 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_fan_id_02.csv
2020-11-30 18:13:58,139 - INFO - AUC : 0.6004985337243401
2020-11-30 18:13:58,140 - INFO - pAUC : 0.7075165920666769
2020-11-30 18:13:58,140 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:58,141 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/fan_id_04
2020-11-30 18:13:58,148 - INFO - test_file  num : 430
2020-11-30 18:13:58,150 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 4/4 [00:00<00:00,  6.54it/s]
2020-11-30 18:13:58,765 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_fan_id_04.csv
2020-11-30 18:13:58,769 - INFO - AUC : 0.5212424242424243
2020-11-30 18:13:58,770 - INFO - pAUC : 0.5137161084529506
2020-11-30 18:13:58,770 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:58,771 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/fan_id_06
2020-11-30 18:13:58,777 - INFO - test_file  num : 443
2020-11-30 18:13:58,778 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/4 [00:00<?, ?it/s]

100%|██████████| 4/4 [00:00<00:00,  6.35it/s]
2020-11-30 18:13:59,412 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_fan_id_06.csv
2020-11-30 18:13:59,415 - INFO - AUC : 0.758600583090379
2020-11-30 18:13:59,416 - INFO - pAUC : 0.7873254564983889
2020-11-30 18:13:59,416 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:13:59,417 - INFO - ===========================
2020-11-30 18:13:59,417 - INFO - [4/6] /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/pump
2020-11-30 18:13:59,418 - INFO - ============== MODEL LOAD ==============
2020-11-30 18:14:00,258 - INFO - ============== CALC GMM PARAM : pump ==============
100%|██████████| 46/46 [00:04<00:00, 11.06it/s]
2020-11-30 18:14:04,421 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/pump_id_00
2020-11-30 18:14:04,424 - INFO - test_file  num : 237
2020-11-30 18:14

N: 5766
phi :
 tensor([9.4239e-05, 1.8104e-04, 9.9972e-01])
mu :
 tensor([[ 0.2628, -0.3373,  0.1569,  0.3464, -0.2987,  0.1444],
        [ 0.4178, -0.5877,  0.4706,  0.5951, -0.4816,  0.1104],
        [ 0.0232, -0.0173, -0.0336,  0.0171, -0.0137,  0.0665]])
cov :
 tensor([[[ 0.0742, -0.0783, -0.0484,  0.0819, -0.0801, -0.0249],
         [-0.0783,  0.0873,  0.0459, -0.0890,  0.0878,  0.0250],
         [-0.0484,  0.0459,  0.0591, -0.0507,  0.0515,  0.0258],
         [ 0.0819, -0.0890, -0.0507,  0.0944, -0.0907, -0.0246],
         [-0.0801,  0.0878,  0.0515, -0.0907,  0.0901,  0.0248],
         [-0.0249,  0.0250,  0.0258, -0.0246,  0.0248,  0.0327]],

        [[ 0.0264, -0.0286, -0.0138,  0.0298, -0.0289, -0.0059],
         [-0.0286,  0.0331,  0.0124, -0.0333,  0.0327,  0.0058],
         [-0.0138,  0.0124,  0.0206, -0.0141,  0.0149,  0.0064],
         [ 0.0298, -0.0333, -0.0141,  0.0352, -0.0333, -0.0057],
         [-0.0289,  0.0327,  0.0149, -0.0333,  0.0331,  0.0058],
         [-0.0059

100%|██████████| 2/2 [00:00<00:00,  4.28it/s]
2020-11-30 18:14:04,895 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_pump_id_00.csv
2020-11-30 18:14:04,899 - INFO - AUC : 0.8621897810218978
2020-11-30 18:14:04,901 - INFO - pAUC : 0.5420668459469843
2020-11-30 18:14:04,901 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:04,902 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/pump_id_02
2020-11-30 18:14:04,906 - INFO - test_file  num : 205
2020-11-30 18:14:04,907 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  4.85it/s]
2020-11-30 18:14:05,322 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_pump_id_02.csv
2020-11-30 18:14:05,325 - INFO - AUC : 0.7627619047619048
2020-11-30 18:14:05,326 - INFO - pAUC : 0.6090225563909775
2020-11-30 18:14:05,326 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:05,328 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/pump_id_04
2020-11-30 18:14:05,332 - INFO - test_file  num : 194
2020-11-30 18:14:05,332 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  4.87it/s]
2020-11-30 18:14:05,746 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_pump_id_04.csv
2020-11-30 18:14:05,749 - INFO - AUC : 0.41595744680851066
2020-11-30 18:14:05,749 - INFO - pAUC : 0.49720044792833146
2020-11-30 18:14:05,750 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:05,750 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/pump_id_06
2020-11-30 18:14:05,755 - INFO - test_file  num : 196
2020-11-30 18:14:05,755 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  4.78it/s]
2020-11-30 18:14:06,176 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_pump_id_06.csv
2020-11-30 18:14:06,180 - INFO - AUC : 0.31645833333333334
2020-11-30 18:14:06,181 - INFO - pAUC : 0.47971491228070173
2020-11-30 18:14:06,181 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:06,182 - INFO - ===========================
2020-11-30 18:14:06,182 - INFO - [5/6] /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/slider
2020-11-30 18:14:06,183 - INFO - ============== MODEL LOAD ==============
2020-11-30 18:14:07,042 - INFO - ============== CALC GMM PARAM : slider ==============
100%|██████████| 41/41 [00:03<00:00, 10.85it/s]
2020-11-30 18:14:10,824 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/slider_id_00
2020-11-30 18:14:10,828 - INFO - test_file  num : 445
2020-1

N: 5174
phi :
 tensor([1.9411e-04, 9.9947e-01, 3.3641e-04])
mu :
 tensor([[ 0.4109, -0.4050, -0.4106, -0.4106, -0.4181,  0.4649],
        [-0.0315,  0.0209,  0.0201,  0.0276,  0.0190,  0.0546],
        [ 0.4110, -0.4090, -0.4119, -0.4113, -0.4176,  0.4667]])
cov :
 tensor([[[ 0.1332, -0.1307, -0.1311, -0.1320, -0.1324,  0.1302],
         [-0.1307,  0.1336,  0.1307,  0.1305,  0.1290, -0.1293],
         [-0.1311,  0.1307,  0.1333,  0.1311,  0.1298, -0.1298],
         [-0.1320,  0.1305,  0.1311,  0.1338,  0.1328, -0.1300],
         [-0.1324,  0.1290,  0.1298,  0.1328,  0.1331, -0.1294],
         [ 0.1302, -0.1293, -0.1298, -0.1300, -0.1294,  0.1327]],

        [[ 0.0056, -0.0037, -0.0030, -0.0039, -0.0054,  0.0031],
         [-0.0037,  0.0067,  0.0026,  0.0031,  0.0029, -0.0027],
         [-0.0030,  0.0026,  0.0068,  0.0028,  0.0021, -0.0028],
         [-0.0039,  0.0031,  0.0028,  0.0061,  0.0058, -0.0028],
         [-0.0054,  0.0029,  0.0021,  0.0058,  0.0068, -0.0031],
         [ 0.0031

100%|██████████| 4/4 [00:00<00:00,  6.44it/s]
2020-11-30 18:14:11,453 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_slider_id_00.csv
2020-11-30 18:14:11,456 - INFO - AUC : 0.6200579710144928
2020-11-30 18:14:11,457 - INFO - pAUC : 0.7351639969488941
2020-11-30 18:14:11,457 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:11,458 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/slider_id_02
2020-11-30 18:14:11,463 - INFO - test_file  num : 356
2020-11-30 18:14:11,464 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00,  5.49it/s]
2020-11-30 18:14:12,014 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_slider_id_02.csv
2020-11-30 18:14:12,018 - INFO - AUC : 0.4845703125
2020-11-30 18:14:12,019 - INFO - pAUC : 0.6521381578947368
2020-11-30 18:14:12,019 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:12,020 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/slider_id_04
2020-11-30 18:14:12,024 - INFO - test_file  num : 267
2020-11-30 18:14:12,025 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/3 [00:00<?, ?it/s]

100%|██████████| 3/3 [00:00<00:00,  6.21it/s]
2020-11-30 18:14:12,512 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_slider_id_04.csv
2020-11-30 18:14:12,515 - INFO - AUC : 0.9005988023952095
2020-11-30 18:14:12,515 - INFO - pAUC : 0.8751969744721084
2020-11-30 18:14:12,516 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:12,516 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/slider_id_06
2020-11-30 18:14:12,521 - INFO - test_file  num : 178
2020-11-30 18:14:12,522 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  5.34it/s]
2020-11-30 18:14:12,899 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_slider_id_06.csv
2020-11-30 18:14:12,902 - INFO - AUC : 0.8042307692307693
2020-11-30 18:14:12,903 - INFO - pAUC : 0.7139001349527665
2020-11-30 18:14:12,903 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:12,904 - INFO - ===========================
2020-11-30 18:14:12,904 - INFO - [6/6] /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/valve
2020-11-30 18:14:12,906 - INFO - ============== MODEL LOAD ==============
2020-11-30 18:14:13,743 - INFO - ============== CALC GMM PARAM : valve ==============
100%|██████████| 46/46 [00:04<00:00, 11.15it/s]
2020-11-30 18:14:17,871 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/valve_id_00
2020-11-30 18:14:17,875 - INFO - test_file  num : 213
2020-11-3

N: 5822
phi :
 tensor([0.0056, 0.0063, 0.9881])
mu :
 tensor([[ 0.1357, -0.1275, -0.1340, -0.1349, -0.1271,  0.1523],
        [ 0.1350, -0.1273, -0.1331, -0.1335, -0.1271,  0.1486],
        [-0.0062,  0.0062,  0.0080,  0.0095,  0.0077,  0.0648]])
cov :
 tensor([[[ 0.0661, -0.0619, -0.0661, -0.0670, -0.0629,  0.0356],
         [-0.0619,  0.0582,  0.0617,  0.0627,  0.0588, -0.0335],
         [-0.0661,  0.0617,  0.0666,  0.0673,  0.0631, -0.0356],
         [-0.0670,  0.0627,  0.0673,  0.0684,  0.0635, -0.0363],
         [-0.0629,  0.0588,  0.0631,  0.0635,  0.0603, -0.0341],
         [ 0.0356, -0.0335, -0.0356, -0.0363, -0.0341,  0.0346]],

        [[ 0.0649, -0.0609, -0.0649, -0.0657, -0.0618,  0.0341],
         [-0.0609,  0.0574,  0.0607,  0.0615,  0.0579, -0.0321],
         [-0.0649,  0.0607,  0.0652,  0.0659,  0.0619, -0.0342],
         [-0.0657,  0.0615,  0.0659,  0.0669,  0.0623, -0.0348],
         [-0.0618,  0.0579,  0.0619,  0.0623,  0.0593, -0.0327],
         [ 0.0341, -0.0321, -

100%|██████████| 2/2 [00:00<00:00,  4.70it/s]
2020-11-30 18:14:18,305 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_valve_id_00.csv
2020-11-30 18:14:18,308 - INFO - AUC : 0.6691150442477877
2020-11-30 18:14:18,309 - INFO - pAUC : 0.5556590591523055
2020-11-30 18:14:18,310 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:18,310 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/valve_id_02
2020-11-30 18:14:18,315 - INFO - test_file  num : 214
2020-11-30 18:14:18,315 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  4.81it/s]
2020-11-30 18:14:18,734 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_valve_id_02.csv
2020-11-30 18:14:18,737 - INFO - AUC : 0.45026315789473687
2020-11-30 18:14:18,737 - INFO - pAUC : 0.49584487534626037
2020-11-30 18:14:18,738 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:18,739 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/valve_id_04
2020-11-30 18:14:18,743 - INFO - test_file  num : 214
2020-11-30 18:14:18,743 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  4.67it/s]
2020-11-30 18:14:19,175 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_valve_id_04.csv
2020-11-30 18:14:19,178 - INFO - AUC : 0.787719298245614
2020-11-30 18:14:19,178 - INFO - pAUC : 0.5304709141274239
2020-11-30 18:14:19,179 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:19,179 - INFO - target_dir : /media/hiroki/working/research/dcase2020/datasets/DCASE2/dev_data/valve_id_06
2020-11-30 18:14:19,183 - INFO - test_file  num : 214
2020-11-30 18:14:19,184 - INFO - ============== BEGIN TEST FOR A MACHINE ID ==============
  0%|          | 0/2 [00:00<?, ?it/s]

100%|██████████| 2/2 [00:00<00:00,  4.57it/s]
2020-11-30 18:14:19,625 - INFO - anomaly score result ->  /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/anomaly_score_valve_id_06.csv
2020-11-30 18:14:19,629 - INFO - AUC : 0.6468421052631579
2020-11-30 18:14:19,630 - INFO - pAUC : 0.5124653739612188
2020-11-30 18:14:19,630 - INFO - ============ END OF TEST FOR A MACHINE ID ============
2020-11-30 18:14:19,631 - INFO - AUC and pAUC results -> /media/hiroki/working/research/dcase2020/result/2D/DAGMM/strict_comp/latent5_mixture3/result/result.csv
